// Jenkinsfile
pipeline {
    agent any

    tools {
        nodejs 'NodeJS 16.4.0'
    }

    stages {
        // stage('Build') {
        //     steps {
        //         dir('frontend/love_signal') {
        //             sh 'npm install'
        //             sh 'npm run build'
        //         }
        //     }
        // }

        stage('Copy files to remote server') {
            steps {
                sshagent([credentials: ['SSH_CREDENTIAL']]) {
                    sh """
                        ssh ubuntu@k8b309.p.ssafy.io "
                            rm -rf /var/www/fe_develop
                            mkdir -p /var/www/fe_develop
                        "
                        scp -r ${WORKSPACE}/frontend ubuntu@k8b309.p.ssafy.io:/var/www/fe_develop
                    """
                }
            }
        }

        stage('Deploy') {
            steps {
                sshagent([credentials: ['SSH_CREDENTIAL']]) {
                    sh """
                        ssh ubuntu@k8b309.p.ssafy.io "
                            cd /var/www/fe_develop/frontend
                            docker compose -f docker-compose-dev.yml down
                            docker compose -f docker-compose-dev.yml up -d
                        "
                    """
                }
            }
        }
    }
    post {
        success {
            mattermostSend(
                color: 'good',
                message: "SUCCESS: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})",
                channel: 'jenkins-bot',
                endpoint: 'https://meeting.ssafy.com/hooks/pzxo89wfpt8c9pzqnymyes9gwc'
            )
        }
        failure {
            mattermostSend(
                color: 'danger',
                message: "FAILURE: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})",
                channel: 'jenkins-bot',
                endpoint: 'https://meeting.ssafy.com/hooks/pzxo89wfpt8c9pzqnymyes9gwc'
            )
        }
    }
}
