/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Heart(props: any) {
  const group = useRef();
  const { nodes, materials }: any = useGLTF("/models/heart.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.7}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Heart_Heart_0.geometry}
              material={materials.Heart}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={0.7}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Marble_Marble_0.geometry}
              material={materials.Marble}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/heart.glb");
